export const FETCH_STARTED = "SEARCH_TYPE/POKE_DATA/FETCH_STARTED";
export const FETCH_SUCCESS = "SEARCH_TYPE/POKE_DATA/FETCH_SUCCESS";
export const FETCH_FAILED = "SEARCH_TYPE/POKE_DATA/FETCH_FAILED";
