export const FETCH_STARTED = "SEARCH_PARTNER/POKE_SPECIES/FETCH_STARTED";
export const FETCH_SUCCESS = "SEARCH_PARTNER/POKE_SPECIES/FETCH_SUCCESS";
export const FETCH_FAILED = "SEARCH_PARTNER/POKE_SPECIES/FETCH_FAILED";
