// type1
export const POKE_TYPE1_STARTED = "SEARCH_TYPE/POKE_TYPE1_DATA/FETCH_STARTED";
export const POKE_TYPE1_SUCCESS = "SEARCH_TYPE/POKE_TYPE1_DATA/FETCH_SUCCESS";
export const POKE_TYPE1_FAILED = "SEARCH_TYPE/POKE_TYPE1_DATA/FETCH_FAILED";

// type2
export const POKE_TYPE2_STARTED = "SEARCH_TYPE/POKE_TYPE2_DATA/FETCH_STARTED";
export const POKE_TYPE2_SUCCESS = "SEARCH_TYPE/POKE_TYPE2_DATA/FETCH_SUCCESS";
export const POKE_TYPE2_FAILED = "SEARCH_TYPE/POKE_TYPE2_DATA/FETCH_FAILED";
