// searchName
export const SEARCH_NAME_STARTED = "SEARCH_NAME/POKE_SPECIES/FETCH_STARTED";
export const SEARCH_NAME_SUCCESS = "SEARCH_NAME/POKE_SPECIES/FETCH_SUCCESS";
export const SEARCH_NAME_FAILED = "SEARCH_NAME/POKE_SPECIES/FETCH_FAILED";

// searchType
export const SEARCH_TYPE_STARTED = "SEARCH_TYPE/POKE_SPECIES/FETCH_STARTED";
export const SEARCH_TYPE_SUCCESS = "SEARCH_TYPE/POKE_SPECIES/FETCH_SUCCESS";
export const SEARCH_TYPE_FAILED = "SEARCH_TYPE/POKE_SPECIES/FETCH_FAILED";
export const SEARCH_TYPE_RESET = "SEARCH_TYPE/POKE_SPECIES/DATA_RESET";

// searchPartner
export const SEARCH_PARTNER_STARTED =
	"SEARCH_PARTNER/POKE_SPECIES/FETCH_STARTED";
export const SEARCH_PARTNER_SUCCESS =
	"SEARCH_PARTNER/POKE_SPECIES/FETCH_SUCCESS";
export const SEARCH_PARTNER_FAILED = "SEARCH_PARTNER/POKE_SPECIES/FETCH_FAILED";
