// searchPoke
export const SEARCH_POKE_STARTED = "SEARCH_POKE/POKE_DATA/FETCH_STARTED";
export const SEARCH_POKE_SUCCESS = "SEARCH_POKE/POKE_DATA/FETCH_SUCCESS";
export const SEARCH_POKE_FAILED = "SEARCH_POKE/POKE_DATA/FETCH_FAILED";

// searchType
export const SEARCH_TYPE_STARTED = "SEARCH_TYPE/POKE_DATA/FETCH_STARTED";
export const SEARCH_TYPE_SUCCESS = "SEARCH_TYPE/POKE_DATA/FETCH_SUCCESS";
export const SEARCH_TYPE_FAILED = "SEARCH_TYPE/POKE_DATA/FETCH_FAILED";

// searchPartner
export const SEARCH_PARTNER_STARTED = "SEARCH_PARTNER/POKE_DATA/FETCH_STARTED";
export const SEARCH_PARTNER_SUCCESS = "SEARCH_PARTNER/POKE_DATA/FETCH_SUCCESS";
export const SEARCH_PARTNER_FAILED = "SEARCH_PARTNER/POKE_DATA/FETCH_FAILED";
