// searchName
export const SEARCH_NAME_STARTED = "SEARCH_NAME/POKE_DATA/FETCH_STARTED";
export const SEARCH_NAME_SUCCESS = "SEARCH_NAME/POKE_DATA/FETCH_SUCCESS";
export const SEARCH_NAME_FAILED = "SEARCH_NAME/POKE_DATA/FETCH_FAILED";

// searchType
export const SEARCH_TYPE_STARTED = "SEARCH_TYPE/POKE_DATA/FETCH_STARTED";
export const SEARCH_TYPE_SUCCESS = "SEARCH_TYPE/POKE_DATA/FETCH_SUCCESS";
export const SEARCH_TYPE_FAILED = "SEARCH_TYPE/POKE_DATA/FETCH_FAILED";

// searchPartner
export const SEARCH_PARTNER_STARTED = "SEARCH_PARTNER/POKE_DATA/FETCH_STARTED";
export const SEARCH_PARTNER_SUCCESS = "SEARCH_PARTNER/POKE_DATA/FETCH_SUCCESS";
export const SEARCH_PARTNER_FAILED = "SEARCH_PARTNER/POKE_DATA/FETCH_FAILED";
